In [1]:
import pandas as pd
import numpy as np
import os
import time

import json

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

## 1. Load data

In [3]:
REGION = 'kr'
TIER = 'GOLD'
DIVISION = 'I'

In [4]:
dfs = []
for filename in os.listdir('./data/tft_match_data_pandas/'):
    if f'{REGION}_{TIER}_{DIVISION}' in filename:
        df_ = pd.read_parquet(f'./data/tft_match_data_pandas/{filename}')
        dfs.append(df_)

In [5]:
df = pd.concat(dfs, axis=0)

In [6]:
df.head()

,metadata.data_version,metadata.match_id,metadata.participants,info.endOfGameResult,info.gameCreation,info.gameId,info.game_datetime,info.game_length,info.game_version,info.mapId,info.participants,info.queueId,info.queue_id,info.tft_game_type,info.tft_set_core_name,info.tft_set_number
0,6,KR_7491534598,[20nK8YPS-5BL-ca5mgsX3HWeGpsWLdtYzWUs9MRWSLGr0...,GameComplete,1737915614000,7491534598,1737917917153,2248.516357,Linux Version 15.2.652.1536 (Jan 23 2025/09:50...,22,{'companion': {'content_ID': '67d000a4-7624-4b...,1100,1100,standard,TFTSet13,13
0,6,KR_7491534598,[20nK8YPS-5BL-ca5mgsX3HWeGpsWLdtYzWUs9MRWSLGr0...,GameComplete,1737915614000,7491534598,1737917917153,2248.516357,Linux Version 15.2.652.1536 (Jan 23 2025/09:50...,22,{'companion': {'content_ID': '25b1326b-341a-4e...,1100,1100,standard,TFTSet13,13
0,6,KR_7491534598,[20nK8YPS-5BL-ca5mgsX3HWeGpsWLdtYzWUs9MRWSLGr0...,GameComplete,1737915614000,7491534598,1737917917153,2248.516357,Linux Version 15.2.652.1536 (Jan 23 2025/09:50...,22,{'companion': {'content_ID': '52fbe476-4038-43...,1100,1100,standard,TFTSet13,13
0,6,KR_7491534598,[20nK8YPS-5BL-ca5mgsX3HWeGpsWLdtYzWUs9MRWSLGr0...,GameComplete,1737915614000,7491534598,1737917917153,2248.516357,Linux Version 15.2.652.1536 (Jan 23 2025/09:50...,22,{'companion': {'content_ID': '25b1326b-341a-4e...,1100,1100,standard,TFTSet13,13
0,6,KR_7491534598,[20nK8YPS-5BL-ca5mgsX3HWeGpsWLdtYzWUs9MRWSLGr0...,GameComplete,1737915614000,7491534598,1737917917153,2248.516357,Linux Version 15.2.652.1536 (Jan 23 2025/09:50...,22,{'companion': {'content_ID': '3d122ca5-58ad-43...,1100,1100,standard,TFTSet13,13

In [7]:
df['metadata.match_id'].nunique()

21004

In [8]:
df.shape

(168032, 16)

In [9]:
# filter for rank matches (queue id = 1100)
df = df.loc[df['info.queueId'] == 1100]

In [10]:
df.shape

(110112, 16)

In [11]:
df.columns

Index(['metadata.data_version', 'metadata.match_id', 'metadata.participants',
       'info.endOfGameResult', 'info.gameCreation', 'info.gameId',
       'info.game_datetime', 'info.game_length', 'info.game_version',
       'info.mapId', 'info.participants', 'info.queueId', 'info.queue_id',
       'info.tft_game_type', 'info.tft_set_core_name', 'info.tft_set_number'],
      dtype='object')

In [12]:
df = pd.concat([df.reset_index(), pd.json_normalize(df['info.participants'])], axis=1)

In [13]:
df.head()

,index,metadata.data_version,metadata.match_id,metadata.participants,info.endOfGameResult,info.gameCreation,info.gameId,info.game_datetime,info.game_length,info.game_version,info.mapId,info.participants,info.queueId,info.queue_id,info.tft_game_type,info.tft_set_core_name,info.tft_set_number,gold_left,last_round,level,partner_group_id,placement,players_eliminated,puuid,riotIdGameName,riotIdTagline,skill_tree,time_eliminated,total_damage_to_players,traits,units,win,companion.content_ID,companion.item_ID,companion.skin_ID,companion.species,missions.PlayerScore2,missions
0,0,6,KR_7491534598,[20nK8YPS-5BL-ca5mgsX3HWeGpsWLdtYzWUs9MRWSLGr0...,GameComplete,1737915614000,7491534598,1737917917153,2248.516357,Linux Version 15.2.652.1536 (Jan 23 2025/09:50...,22,{'companion': {'content_ID': '67d000a4-7624-4b...,1100,1100,standard,TFTSet13,13,0,35,8,None,4,2,20nK8YPS-5BL-ca5mgsX3HWeGpsWLdtYzWUs9MRWSLGr0K...,토라미노,KR1,None,2089.960205,110,"[{'name': 'TFT13_Bruiser', 'num_units': 1, 'st...","[{'character_id': 'TFT13_Draven', 'itemNames':...",True,67d000a4-7624-4b0f-991d-eae9c90f92cc,48003,3,PetChibiAshe,209.0,NaN
1,0,6,KR_7491534598,[20nK8YPS-5BL-ca5mgsX3HWeGpsWLdtYzWUs9MRWSLGr0...,GameComplete,1737915614000,7491534598,1737917917153,2248.516357,Linux Version 15.2.652.1536 (Jan 23 2025/09:50...,22,{'companion': {'content_ID': '25b1326b-341a-4e...,1100,1100,standard,TFTSet13,13,1,35,8,None,3,1,pK2H19GGyoV-UcICU9AoGpNfc3eTm4aZ_oRs6DAcDGEv5s...,와 키,KR1,None,2096.769287,120,"[{'name': 'TFT13_Ambassador', 'num_units': 1, ...","[{'character_id': 'TFT13_Amumu', 'itemNames': ...",True,25b1326b-341a-4e36-a175-1d39872231bd,66007,7,PetPoro,209.0,NaN
2,0,6,KR_7491534598,[20nK8YPS-5BL-ca5mgsX3HWeGpsWLdtYzWUs9MRWSLGr0...,GameComplete,1737915614000,7491534598,1737917917153,2248.516357,Linux Version 15.2.652.1536 (Jan 23 2025/09:50...,22,{'companion': {'content_ID': '52fbe476-4038-43...,1100,1100,standard,TFTSet13,13,32,38,9,None,1,2,lTYm9Wn5ub-OEAkzCERLKDr3b1az4RCVJurOlaujDAureG...,풍자이국주박나래화사,KR1,None,2235.349121,199,"[{'name': 'TFT13_Ambassador', 'num_units': 1, ...","[{'character_id': 'TFT13_Camille', 'itemNames'...",True,52fbe476-4038-432f-b94e-42914f921320,3016,16,PetGrumpyLion,223.0,NaN
3,0,6,KR_7491534598,[20nK8YPS-5BL-ca5mgsX3HWeGpsWLdtYzWUs9MRWSLGr0...,GameComplete,1737915614000,7491534598,1737917917153,2248.516357,Linux Version 15.2.652.1536 (Jan 23 2025/09:50...,22,{'companion': {'content_ID': '25b1326b-341a-4e...,1100,1100,standard,TFTSet13,13,0,30,7,None,6,0,8c4Y48OU3vWU6TgPNqxhHCnmPnZx9xkIAMsMaT2eOaddft...,넌패배자야,KR1,None,1793.041138,71,"[{'name': 'TFT13_Academy', 'num_units': 1, 'st...","[{'character_id': 'TFT13_Morgana', 'itemNames'...",False,25b1326b-341a-4e36-a175-1d39872231bd,66007,7,PetPoro,89.0,NaN
4,0,6,KR_7491534598,[20nK8YPS-5BL-ca5mgsX3HWeGpsWLdtYzWUs9MRWSLGr0...,GameComplete,1737915614000,7491534598,1737917917153,2248.516357,Linux Version 15.2.652.1536 (Jan 23 2025/09:50...,22,{'companion': {'content_ID': '3d122ca5-58ad-43...,1100,1100,standard,TFTSet13,13,1,26,8,None,8,0,c5C9pDtuarWL2BYhp8QEk4mUHyWWSfKU8MZ0VQDCZEkjlk...,tjcodnjs,9876,None,1567.391846,28,"[{'name': 'TFT13_Academy', 'num_units': 2, 'st...","[{'character_id': 'TFT13_Irelia', 'itemNames':...",False,3d122ca5-58ad-43a8-b725-a48b53ff6a3f,11031,31,PetSGPig,78.0,NaN

## 2. Select columns to keep

In [14]:
# select columns to keep
COLS_TO_KEEP = ['metadata.data_version', 'metadata.match_id', 'info.endOfGameResult',
               'info.gameCreation', 'info.game_datetime', 'info.game_length', 'info.game_version',
               'info.mapId', 'info.queueId', 'info.tft_game_type', 'info.tft_set_core_name',
               'info.tft_set_number', 'gold_left', 'last_round', 'level', 'partner_group_id', 'placement',
               'players_eliminated', 'puuid', 'riotIdGameName', 'riotIdTagline',
               'skill_tree', 'time_eliminated', 'total_damage_to_players', 'traits',
               'units', 'win',]

df = df[COLS_TO_KEEP]

In [15]:
df.columns = df.columns.str.replace('.', '_', regex=False)

df.columns

Index(['metadata_data_version', 'metadata_match_id', 'info_endOfGameResult',
       'info_gameCreation', 'info_game_datetime', 'info_game_length',
       'info_game_version', 'info_mapId', 'info_queueId', 'info_tft_game_type',
       'info_tft_set_core_name', 'info_tft_set_number', 'gold_left',
       'last_round', 'level', 'partner_group_id', 'placement',
       'players_eliminated', 'puuid', 'riotIdGameName', 'riotIdTagline',
       'skill_tree', 'time_eliminated', 'total_damage_to_players', 'traits',
       'units', 'win'],
      dtype='object')

In [16]:
df.head()

,metadata_data_version,metadata_match_id,info_endOfGameResult,info_gameCreation,info_game_datetime,info_game_length,info_game_version,info_mapId,info_queueId,info_tft_game_type,info_tft_set_core_name,info_tft_set_number,gold_left,last_round,level,partner_group_id,placement,players_eliminated,puuid,riotIdGameName,riotIdTagline,skill_tree,time_eliminated,total_damage_to_players,traits,units,win
0,6,KR_7491534598,GameComplete,1737915614000,1737917917153,2248.516357,Linux Version 15.2.652.1536 (Jan 23 2025/09:50...,22,1100,standard,TFTSet13,13,0,35,8,None,4,2,20nK8YPS-5BL-ca5mgsX3HWeGpsWLdtYzWUs9MRWSLGr0K...,토라미노,KR1,None,2089.960205,110,"[{'name': 'TFT13_Bruiser', 'num_units': 1, 'st...","[{'character_id': 'TFT13_Draven', 'itemNames':...",True
1,6,KR_7491534598,GameComplete,1737915614000,1737917917153,2248.516357,Linux Version 15.2.652.1536 (Jan 23 2025/09:50...,22,1100,standard,TFTSet13,13,1,35,8,None,3,1,pK2H19GGyoV-UcICU9AoGpNfc3eTm4aZ_oRs6DAcDGEv5s...,와 키,KR1,None,2096.769287,120,"[{'name': 'TFT13_Ambassador', 'num_units': 1, ...","[{'character_id': 'TFT13_Amumu', 'itemNames': ...",True
2,6,KR_7491534598,GameComplete,1737915614000,1737917917153,2248.516357,Linux Version 15.2.652.1536 (Jan 23 2025/09:50...,22,1100,standard,TFTSet13,13,32,38,9,None,1,2,lTYm9Wn5ub-OEAkzCERLKDr3b1az4RCVJurOlaujDAureG...,풍자이국주박나래화사,KR1,None,2235.349121,199,"[{'name': 'TFT13_Ambassador', 'num_units': 1, ...","[{'character_id': 'TFT13_Camille', 'itemNames'...",True
3,6,KR_7491534598,GameComplete,1737915614000,1737917917153,2248.516357,Linux Version 15.2.652.1536 (Jan 23 2025/09:50...,22,1100,standard,TFTSet13,13,0,30,7,None,6,0,8c4Y48OU3vWU6TgPNqxhHCnmPnZx9xkIAMsMaT2eOaddft...,넌패배자야,KR1,None,1793.041138,71,"[{'name': 'TFT13_Academy', 'num_units': 1, 'st...","[{'character_id': 'TFT13_Morgana', 'itemNames'...",False
4,6,KR_7491534598,GameComplete,1737915614000,1737917917153,2248.516357,Linux Version 15.2.652.1536 (Jan 23 2025/09:50...,22,1100,standard,TFTSet13,13,1,26,8,None,8,0,c5C9pDtuarWL2BYhp8QEk4mUHyWWSfKU8MZ0VQDCZEkjlk...,tjcodnjs,9876,None,1567.391846,28,"[{'name': 'TFT13_Academy', 'num_units': 2, 'st...","[{'character_id': 'TFT13_Irelia', 'itemNames':...",False

In [17]:
df.shape

(110112, 27)

In [18]:
df.shape[0] / 8

13764.0

## 3. Filter last round of 8th players

In [19]:
# only keep matches where all players reached carousel round of stage 4 (avoid early FF matches)
LAST_ROUND = 22        # the last round of the player who went 8th place has to be >= 22

df['match_earliest_last_round'] = df.groupby('metadata_match_id')['last_round'].transform('min')

In [20]:
df.head()

,metadata_data_version,metadata_match_id,info_endOfGameResult,info_gameCreation,info_game_datetime,info_game_length,info_game_version,info_mapId,info_queueId,info_tft_game_type,info_tft_set_core_name,info_tft_set_number,gold_left,last_round,level,partner_group_id,placement,players_eliminated,puuid,riotIdGameName,riotIdTagline,skill_tree,time_eliminated,total_damage_to_players,traits,units,win,match_earliest_last_round
0,6,KR_7491534598,GameComplete,1737915614000,1737917917153,2248.516357,Linux Version 15.2.652.1536 (Jan 23 2025/09:50...,22,1100,standard,TFTSet13,13,0,35,8,None,4,2,20nK8YPS-5BL-ca5mgsX3HWeGpsWLdtYzWUs9MRWSLGr0K...,토라미노,KR1,None,2089.960205,110,"[{'name': 'TFT13_Bruiser', 'num_units': 1, 'st...","[{'character_id': 'TFT13_Draven', 'itemNames':...",True,26
1,6,KR_7491534598,GameComplete,1737915614000,1737917917153,2248.516357,Linux Version 15.2.652.1536 (Jan 23 2025/09:50...,22,1100,standard,TFTSet13,13,1,35,8,None,3,1,pK2H19GGyoV-UcICU9AoGpNfc3eTm4aZ_oRs6DAcDGEv5s...,와 키,KR1,None,2096.769287,120,"[{'name': 'TFT13_Ambassador', 'num_units': 1, ...","[{'character_id': 'TFT13_Amumu', 'itemNames': ...",True,26
2,6,KR_7491534598,GameComplete,1737915614000,1737917917153,2248.516357,Linux Version 15.2.652.1536 (Jan 23 2025/09:50...,22,1100,standard,TFTSet13,13,32,38,9,None,1,2,lTYm9Wn5ub-OEAkzCERLKDr3b1az4RCVJurOlaujDAureG...,풍자이국주박나래화사,KR1,None,2235.349121,199,"[{'name': 'TFT13_Ambassador', 'num_units': 1, ...","[{'character_id': 'TFT13_Camille', 'itemNames'...",True,26
3,6,KR_7491534598,GameComplete,1737915614000,1737917917153,2248.516357,Linux Version 15.2.652.1536 (Jan 23 2025/09:50...,22,1100,standard,TFTSet13,13,0,30,7,None,6,0,8c4Y48OU3vWU6TgPNqxhHCnmPnZx9xkIAMsMaT2eOaddft...,넌패배자야,KR1,None,1793.041138,71,"[{'name': 'TFT13_Academy', 'num_units': 1, 'st...","[{'character_id': 'TFT13_Morgana', 'itemNames'...",False,26
4,6,KR_7491534598,GameComplete,1737915614000,1737917917153,2248.516357,Linux Version 15.2.652.1536 (Jan 23 2025/09:50...,22,1100,standard,TFTSet13,13,1,26,8,None,8,0,c5C9pDtuarWL2BYhp8QEk4mUHyWWSfKU8MZ0VQDCZEkjlk...,tjcodnjs,9876,None,1567.391846,28,"[{'name': 'TFT13_Academy', 'num_units': 2, 'st...","[{'character_id': 'TFT13_Irelia', 'itemNames':...",False,26

In [21]:
df = df.loc[df['match_earliest_last_round'] >= 22]

In [22]:
df.shape

(87880, 28)

In [23]:
df.shape[0] / 8

10985.0

In [24]:
df.drop('match_earliest_last_round', axis=1, inplace=True)

## 4. Exclude games where some players sell all their board before FF

In [25]:
# some games players will sell all their board before early surrendering, we will also exclude those matches
df['unit_count'] = df['units'].apply(len)
df['match_min_unit_count'] = df.groupby('metadata_match_id')['unit_count'].transform(min)

df.head()

/tmp/ipykernel_25529/2636806920.py:3: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df['match_min_unit_count'] = df.groupby('metadata_match_id')['unit_count'].transform(min)

,metadata_data_version,metadata_match_id,info_endOfGameResult,info_gameCreation,info_game_datetime,info_game_length,info_game_version,info_mapId,info_queueId,info_tft_game_type,info_tft_set_core_name,info_tft_set_number,gold_left,last_round,level,partner_group_id,placement,players_eliminated,puuid,riotIdGameName,riotIdTagline,skill_tree,time_eliminated,total_damage_to_players,traits,units,win,unit_count,match_min_unit_count
0,6,KR_7491534598,GameComplete,1737915614000,1737917917153,2248.516357,Linux Version 15.2.652.1536 (Jan 23 2025/09:50...,22,1100,standard,TFTSet13,13,0,35,8,None,4,2,20nK8YPS-5BL-ca5mgsX3HWeGpsWLdtYzWUs9MRWSLGr0K...,토라미노,KR1,None,2089.960205,110,"[{'name': 'TFT13_Bruiser', 'num_units': 1, 'st...","[{'character_id': 'TFT13_Draven', 'itemNames':...",True,8,7
1,6,KR_7491534598,GameComplete,1737915614000,1737917917153,2248.516357,Linux Version 15.2.652.1536 (Jan 23 2025/09:50...,22,1100,standard,TFTSet13,13,1,35,8,None,3,1,pK2H19GGyoV-UcICU9AoGpNfc3eTm4aZ_oRs6DAcDGEv5s...,와 키,KR1,None,2096.769287,120,"[{'name': 'TFT13_Ambassador', 'num_units': 1, ...","[{'character_id': 'TFT13_Amumu', 'itemNames': ...",True,8,7
2,6,KR_7491534598,GameComplete,1737915614000,1737917917153,2248.516357,Linux Version 15.2.652.1536 (Jan 23 2025/09:50...,22,1100,standard,TFTSet13,13,32,38,9,None,1,2,lTYm9Wn5ub-OEAkzCERLKDr3b1az4RCVJurOlaujDAureG...,풍자이국주박나래화사,KR1,None,2235.349121,199,"[{'name': 'TFT13_Ambassador', 'num_units': 1, ...","[{'character_id': 'TFT13_Camille', 'itemNames'...",True,9,7
3,6,KR_7491534598,GameComplete,1737915614000,1737917917153,2248.516357,Linux Version 15.2.652.1536 (Jan 23 2025/09:50...,22,1100,standard,TFTSet13,13,0,30,7,None,6,0,8c4Y48OU3vWU6TgPNqxhHCnmPnZx9xkIAMsMaT2eOaddft...,넌패배자야,KR1,None,1793.041138,71,"[{'name': 'TFT13_Academy', 'num_units': 1, 'st...","[{'character_id': 'TFT13_Morgana', 'itemNames'...",False,7,7
4,6,KR_7491534598,GameComplete,1737915614000,1737917917153,2248.516357,Linux Version 15.2.652.1536 (Jan 23 2025/09:50...,22,1100,standard,TFTSet13,13,1,26,8,None,8,0,c5C9pDtuarWL2BYhp8QEk4mUHyWWSfKU8MZ0VQDCZEkjlk...,tjcodnjs,9876,None,1567.391846,28,"[{'name': 'TFT13_Academy', 'num_units': 2, 'st...","[{'character_id': 'TFT13_Irelia', 'itemNames':...",False,8,7

In [26]:
# drop matches where there is a player selling all their units (unit count=0)
df = df.loc[df['match_min_unit_count'] > 0]

In [27]:
df.shape

(87704, 29)

In [28]:
df.shape[0] / 8

10963.0

In [29]:
df.drop(['match_min_unit_count', 'unit_count'], axis=1, inplace=True)

## 5. Exclude games with BOTs

In [30]:
df['is_bot'] = (df['puuid'] == 'BOT').astype(int)

df['match_contains_bot'] = df.groupby('metadata_match_id')['is_bot'].transform('max')

In [31]:
# exclude games with bots
df = df.loc[df['match_contains_bot'] == 0]

In [32]:
df.shape

(84688, 29)

In [33]:
df.shape[0] / 8

10586.0

In [34]:
df.drop(['is_bot', 'match_contains_bot'], axis=1, inplace=True)

In [35]:
df.to_parquet(f'./data/tft_match_data_cleaned/matches_{REGION}_{TIER}_{DIVISION}.parquet')